# Generated by Django 5.2.4 on 2025-08-11 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created_at',), 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AddField(
            model_name='order',
            name='consent_pdn',
            field=models.BooleanField(default=False, verbose_name='Согласие на ПДн'),
        ),
        migrations.AddField(
            model_name='order',
            name='consent_ts',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время согласия'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_time_from',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Окно доставки: с'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_time_to',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Окно доставки: до'),
        ),
        migrations.AddField(
            model_name='order',
            name='items_count',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Единиц багажа'),
        ),
        migrations.AddField(
            model_name='order',
            name='photos',
            field=models.JSONField(blank=True, default=list, verbose_name='Фото (URL/путь)'),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_time_from',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Окно забора: с'),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_time_to',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Окно забора: до'),
        ),
        migrations.AddField(
            model_name='order',
            name='promo_code',
            field=models.CharField(blank=True, max_length=32, verbose_name='Промокод'),
        ),
        migrations.AddField(
            model_name='order',
            name='seal_numbers',
            field=models.JSONField(blank=True, default=list, verbose_name='№ пломб (список)'),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E‑mail'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=32, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время забора'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('confirmed', 'Подтверждён'), ('picked_up', 'Забрали'), ('in_storage', 'На складе'), ('out_for_delivery', 'В пути к доставке'), ('delivered', 'Доставлено'), ('canceled', 'Отменён')], db_index=True, default='draft', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='telegram',
            field=models.CharField(blank=True, max_length=64, verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='order',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=64, verbose_name='WhatsApp'),
        ),
    ]
