# Generated by Django 5.2.4 on 2025-08-11 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_order_options_order_consent_pdn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='consent_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP при согласии'),
        ),
        migrations.AddField(
            model_name='order',
            name='consent_ua',
            field=models.CharField(blank=True, max_length=256, verbose_name='User‑Agent при согласии'),
        ),
    ]
