# Generated by Django 5.2.4 on 2025-08-11 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_order_consent_ip_order_consent_ua'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='consent',
            field=models.BooleanField(default=False, help_text='Согласие на обработку ПДн'),
        ),
        migrations.AddField(
            model_name='order',
            name='consent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
