# Generated by Django 5.2.4 on 2025-08-12 14:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_order_public_token_order_telegram_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='public_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
