# Generated by Django 5.2.4 on 2025-08-13 10:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_order_public_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='public_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=32, verbose_name='TG chat id'),
        ),
    ]
