# Generated by Django 5.2.4 on 2025-08-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_order_public_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
