# Generated by Django 5.2.4 on 2025-08-25 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_order_telegram_chat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotifyLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Замок уведомления',
                'verbose_name_plural': 'Замки уведомлений',
            },
        ),
    ]
