# Generated by Django 5.2.4 on 2025-08-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_notifylock'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='last_client_status_notified',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
